// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package html

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de_DE": &dictionary{index: de_DEIndex, data: de_DEData},
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Administrate this Pad":          13,
	"Administrate this pad":          14,
	"Any shift":                      16,
	"Any taker name":                 21,
	"Back":                           10,
	"Begin":                          49,
	"Cancel":                         31,
	"Contact":                        56,
	"Copy iCalendar":                 45,
	"Copy link":                      12,
	"Count":                          52,
	"Create new Pad":                 3,
	"Create share link":              30,
	"Create shifts":                  42,
	"Create, Edit and Delete Shifts": 15,
	"Delete":                         40,
	"Delete shift":                   55,
	"Description (Markdown)":         5,
	"Edit":                           39,
	"Edit retroactively":             17,
	"End":                            50,
	"Error":                          35,
	"Example":                        20,
	"Expires":                        28,
	"Go":                             32,
	"Link Properties":                27,
	"Link expires":                   44,
	"Location":                       6,
	"Name":                           4,
	"Next":                           34,
	"Note":                           29,
	"Please use the full link.":      0,
	"Save":                           9,
	"Save changes":                   57,
	"Settings":                       46,
	"Share":                          47,
	"Shift":                          37,
	"Shift Names (one name per row)": 7,
	"Shift name":                     54,
	"Sorry, internal server error":   1,
	"Sorry, not found":               2,
	"Take":                           41,
	"Take Shifts":                    18,
	"Take deadline (cron expression, optional)": 19,
	"Take shift":                         58,
	"Take shifts as":                     23,
	"Taker":                              38,
	"Taker names":                        22,
	"This":                               33,
	"This is your customized share link": 11,
	"Time":                               36,
	"Unnamed Pad":                        43,
	"View Shifts":                        24,
	"View taker contact":                 26,
	"View taker name":                    25,
	"do not assign to an event":          51,
	"ical Overlay":                       8,
	"last changed":                       48,
	"no shifts available":                53,
}

var de_DEIndex = []uint32{ // 60 elements
	// Entry 0 - 1F
	0x00000000, 0x00000028, 0x00000045, 0x0000005b,
	0x0000006d, 0x00000072, 0x0000008a, 0x00000093,
	0x000000b3, 0x000000c0, 0x000000ca, 0x000000d2,
	0x000000fa, 0x00000108, 0x00000122, 0x0000013c,
	0x00000167, 0x00000174, 0x0000018c, 0x0000019d,
	0x000001d2, 0x000001db, 0x000001e6, 0x000001ec,
	0x00000206, 0x00000219, 0x00000228, 0x00000239,
	0x0000024c, 0x00000258, 0x00000260, 0x00000276,
	// Entry 20 - 3F
	0x00000280, 0x00000284, 0x0000028a, 0x00000293,
	0x0000029a, 0x0000029f, 0x000002a7, 0x000002ac,
	0x000002b7, 0x000002c0, 0x000002c7, 0x000002d9,
	0x000002e9, 0x000002fa, 0x00000312, 0x00000320,
	0x00000327, 0x00000339, 0x00000340, 0x00000345,
	0x0000035d, 0x00000364, 0x0000037e, 0x00000386,
	0x00000397, 0x0000039f, 0x000003b5, 0x000003bc,
} // Size: 264 bytes

const de_DEData string = "" + // Size: 956 bytes
	"\x02Bitte verwende den vollständigen Link.\x02Sorry, interner Serverfehl" +
	"er\x02Sorry, nicht gefunden\x02Neues Pad anlegen\x02Name\x02Beschreibung" +
	" (Markdown)\x02Zeitzone\x02Schicht-Typen (einer pro Zeile)\x02ical-Overl" +
	"ay\x02Speichern\x02Zurück\x02Dies ist dein gewünschter Freigabelink\x02L" +
	"ink kopieren\x02Dieses Pad administrieren\x02Dieses Pad administrieren" +
	"\x02Schichten anlegen, bearbeiten und löschen\x02Jede Schicht\x02Rückwir" +
	"kend bearbeiten\x02Schichten machen\x02Deadline zum Übernehmen (cron-exp" +
	"ression, optional)\x02Beispiel\x02Jeder Name\x02Namen\x02Schichten übern" +
	"ehmen als\x02Schichten anzeigen\x02Namen anzeigen\x02Kontakt anzeigen" +
	"\x02Link-Eigenschaften\x02Gültig bis\x02Hinweis\x02Freigabelink erzeugen" +
	"\x02Abbrechen\x02Los\x02Diese\x02Nächste\x02Fehler\x02Zeit\x02Schicht" +
	"\x02Name\x02Bearbeiten\x02Löschen\x02Machen\x02Schichten anlegen\x02Unbe" +
	"nanntes Pad\x02Link gültig bis\x02iCalendar-Link kopieren\x02Einstellung" +
	"en\x02Teilen\x02zuletzt geändert\x02Beginn\x02Ende\x02keinem Event zugeo" +
	"rdnet\x02Anzahl\x02keine Schichten vorhanden\x02Schicht\x02Schicht lösch" +
	"en\x02Kontakt\x02Änderungen speichern\x02Machen"

var en_USIndex = []uint32{ // 60 elements
	// Entry 0 - 1F
	0x00000000, 0x0000001a, 0x00000037, 0x00000048,
	0x00000057, 0x0000005c, 0x00000073, 0x0000007c,
	0x0000009b, 0x000000a8, 0x000000ad, 0x000000b2,
	0x000000d5, 0x000000df, 0x000000f5, 0x0000010b,
	0x0000012a, 0x00000134, 0x00000147, 0x00000153,
	0x0000017d, 0x00000185, 0x00000194, 0x000001a0,
	0x000001af, 0x000001bb, 0x000001cb, 0x000001de,
	0x000001ee, 0x000001f6, 0x000001fb, 0x0000020d,
	// Entry 20 - 3F
	0x00000214, 0x00000217, 0x0000021c, 0x00000221,
	0x00000227, 0x0000022c, 0x00000232, 0x00000238,
	0x0000023d, 0x00000244, 0x00000249, 0x00000257,
	0x00000263, 0x00000270, 0x0000027f, 0x00000288,
	0x0000028e, 0x0000029b, 0x000002a1, 0x000002a5,
	0x000002bf, 0x000002c5, 0x000002d9, 0x000002e4,
	0x000002f1, 0x000002f9, 0x00000306, 0x00000311,
} // Size: 264 bytes

const en_USData string = "" + // Size: 785 bytes
	"\x02Please use the full link.\x02Sorry, internal server error\x02Sorry, " +
	"not found\x02Create new Pad\x02Name\x02Description (Markdown)\x02Locatio" +
	"n\x02Shift Names (one name per row)\x02ical Overlay\x02Save\x02Back\x02T" +
	"his is your customized share link\x02Copy link\x02Administrate this Pad" +
	"\x02Administrate this pad\x02Create, Edit and Delete Shifts\x02Any shift" +
	"\x02Edit retroactively\x02Take Shifts\x02Take deadline (cron expression," +
	" optional)\x02Example\x02Any taker name\x02Taker names\x02Take shifts as" +
	"\x02View Shifts\x02View taker name\x02View taker contact\x02Link Propert" +
	"ies\x02Expires\x02Note\x02Create share link\x02Cancel\x02Go\x02This\x02N" +
	"ext\x02Error\x02Time\x02Shift\x02Taker\x02Edit\x02Delete\x02Take\x02Crea" +
	"te shifts\x02Unnamed Pad\x02Link expires\x02Copy iCalendar\x02Settings" +
	"\x02Share\x02last changed\x02Begin\x02End\x02do not assign to an event" +
	"\x02Count\x02no shifts available\x02Shift name\x02Delete shift\x02Contac" +
	"t\x02Save changes\x02Take shift"

	// Total table size 2269 bytes (2KiB); checksum: A865B61D
