// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package html

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de_DE": &dictionary{index: de_DEIndex, data: de_DEData},
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Administrate this Pad":          26,
	"Administrate this pad":          27,
	"Any shift":                      29,
	"Any taker name":                 38,
	"Apply":                          60,
	"Apply for Shifts":               34,
	"Apply for shift":                77,
	"Approve":                        56,
	"Approve take":                   79,
	"Back":                           23,
	"Begin":                          68,
	"Cancel":                         48,
	"Contact":                        75,
	"Copy iCalendar":                 64,
	"Copy link":                      25,
	"Create new Pad":                 3,
	"Create share link":              47,
	"Create shifts":                  61,
	"Create, Edit and Delete Shifts": 28,
	"Cron expression, example":       37,
	"Deadline (optional)":            36,
	"Delete":                         55,
	"Delete shift":                   73,
	"Description (Markdown)":         18,
	"Edit":                           54,
	"Edit retroactively":             30,
	"End":                            69,
	"Error":                          52,
	"Expires":                        45,
	"Go":                             49,
	"Link Properties":                44,
	"Link expires":                   63,
	"Location":                       19,
	"Mark any shift as paid out":     32,
	"Mark as paid out":               16,
	"Name":                           17,
	"Next":                           51,
	"No shifts.":                     13,
	"Note":                           46,
	"Paid out":                       8,
	"Paid shifts taken by":           14,
	"Payout":                         31,
	"Please use the full link.":      0,
	"Quantity":                       53,
	"Save":                           22,
	"Save changes":                   76,
	"Settings":                       65,
	"Share":                          66,
	"Shift":                          6,
	"Shift Names (one name per row)": 20,
	"Shift name":                     71,
	"Sorry, internal server error":   1,
	"Sorry, not found":               2,
	"Sum":                            12,
	"Take":                           59,
	"Take Shifts":                    33,
	"Take and Apply":                 35,
	"Take shift":                     78,
	"Take shifts as":                 40,
	"Taker":                          7,
	"Taker and Approvement":          74,
	"Taker names":                    39,
	"These shifts have been marked as paid out for": 4,
	"This":                               50,
	"This is your customized share link": 24,
	"Time":                               5,
	"Unknown event":                      9,
	"Unnamed Pad":                        62,
	"View Shifts":                        41,
	"View taker contact":                 43,
	"View taker name":                    42,
	"do not assign to an event":          70,
	"hours":                              11,
	"ical Overlay":                       21,
	"last changed":                       67,
	"no shifts available":                72,
	"not paid out yet":                   58,
	"not yet approved":                   15,
	"paid":                               10,
	"paid out":                           57,
}

var de_DEIndex = []uint32{ // 81 elements
	// Entry 0 - 1F
	0x00000000, 0x00000028, 0x00000045, 0x0000005b,
	0x0000006d, 0x000000a1, 0x000000a6, 0x000000ae,
	0x000000b3, 0x000000be, 0x000000d0, 0x000000d8,
	0x000000e0, 0x000000e6, 0x000000f7, 0x0000010e,
	0x00000124, 0x0000013d, 0x00000142, 0x0000015a,
	0x00000163, 0x00000183, 0x00000190, 0x0000019a,
	0x000001a2, 0x000001ca, 0x000001d8, 0x000001f2,
	0x0000020c, 0x00000237, 0x00000244, 0x0000025c,
	// Entry 20 - 3F
	0x00000267, 0x0000028d, 0x000002a6, 0x000002be,
	0x000002e4, 0x000002f8, 0x00000315, 0x00000320,
	0x00000326, 0x00000340, 0x00000353, 0x00000362,
	0x00000373, 0x00000386, 0x00000392, 0x0000039a,
	0x000003b0, 0x000003ba, 0x000003be, 0x000003c4,
	0x000003cd, 0x000003d4, 0x000003db, 0x000003e6,
	0x000003ef, 0x000003f8, 0x00000403, 0x00000419,
	0x00000423, 0x0000042c, 0x0000043e, 0x0000044e,
	// Entry 40 - 5F
	0x0000045f, 0x00000477, 0x00000485, 0x0000048c,
	0x0000049e, 0x000004a5, 0x000004aa, 0x000004c2,
	0x000004ca, 0x000004e4, 0x000004f5, 0x00000507,
	0x0000050f, 0x00000525, 0x0000053a, 0x00000551,
	0x00000564,
} // Size: 348 bytes

const de_DEData string = "" + // Size: 1380 bytes
	"\x02Bitte verwende den vollständigen Link.\x02Sorry, interner Serverfehl" +
	"er\x02Sorry, nicht gefunden\x02Neues Pad anlegen\x02Diese Schichten wurd" +
	"en als ausbezahlt markiert für\x02Zeit\x02Schicht\x02Name\x02Ausbezahlt" +
	"\x02Unbekanntes Event\x02bezahlt\x02Stunden\x02Summe\x02Keine Schichten." +
	"\x02Bezahlte Schichten von\x02noch nicht angenommen\x02Als ausbezahlt ma" +
	"rkieren\x02Name\x02Beschreibung (Markdown)\x02Zeitzone\x02Schicht-Typen " +
	"(einer pro Zeile)\x02ical-Overlay\x02Speichern\x02Zurück\x02Dies ist dei" +
	"n gewünschter Freigabelink\x02Link kopieren\x02Dieses Pad administrieren" +
	"\x02Dieses Pad administrieren\x02Schichten anlegen, bearbeiten und lösch" +
	"en\x02Jede Schicht\x02Rückwirkend bearbeiten\x02Auszahlung\x02Jede Schic" +
	"ht als ausgezahlt markieren\x02Für Schichten eintragen\x02Für Schichten " +
	"bewerben\x02Für Schichten eintragen und bewerben\x02Deadline (optional)" +
	"\x02Cron-Ausdruck, beispielweise\x02Jeder Name\x02Namen\x02Schichten übe" +
	"rnehmen als\x02Schichten anzeigen\x02Namen anzeigen\x02Kontakt anzeigen" +
	"\x02Link-Eigenschaften\x02Gültig bis\x02Hinweis\x02Freigabelink erzeugen" +
	"\x02Abbrechen\x02Los\x02Diese\x02Nächste\x02Fehler\x02Anzahl\x02Bearbeit" +
	"en\x02Löschen\x02Annehmen\x02ausbezahlt\x02noch nicht ausbezahlt\x02Eint" +
	"ragen\x02Bewerben\x02Schichten anlegen\x02Unbenanntes Pad\x02Link gültig" +
	" bis\x02iCalendar-Link kopieren\x02Einstellungen\x02Teilen\x02zuletzt ge" +
	"ändert\x02Beginn\x02Ende\x02keinem Event zugeordnet\x02Schicht\x02keine" +
	" Schichten vorhanden\x02Schicht löschen\x02Namen und Annahme\x02Kontakt" +
	"\x02Änderungen speichern\x02Auf Schicht bewerben\x02Für Schicht eintrage" +
	"n\x02Bewerbung annehmen"

var en_USIndex = []uint32{ // 81 elements
	// Entry 0 - 1F
	0x00000000, 0x0000001a, 0x00000037, 0x00000048,
	0x00000057, 0x00000085, 0x0000008a, 0x00000090,
	0x00000096, 0x0000009f, 0x000000ad, 0x000000b2,
	0x000000b8, 0x000000bc, 0x000000c7, 0x000000dc,
	0x000000ed, 0x000000fe, 0x00000103, 0x0000011a,
	0x00000123, 0x00000142, 0x0000014f, 0x00000154,
	0x00000159, 0x0000017c, 0x00000186, 0x0000019c,
	0x000001b2, 0x000001d1, 0x000001db, 0x000001ee,
	// Entry 20 - 3F
	0x000001f5, 0x00000210, 0x0000021c, 0x0000022d,
	0x0000023c, 0x00000250, 0x00000269, 0x00000278,
	0x00000284, 0x00000293, 0x0000029f, 0x000002af,
	0x000002c2, 0x000002d2, 0x000002da, 0x000002df,
	0x000002f1, 0x000002f8, 0x000002fb, 0x00000300,
	0x00000305, 0x0000030b, 0x00000314, 0x00000319,
	0x00000320, 0x00000328, 0x00000331, 0x00000342,
	0x00000347, 0x0000034d, 0x0000035b, 0x00000367,
	// Entry 40 - 5F
	0x00000374, 0x00000383, 0x0000038c, 0x00000392,
	0x0000039f, 0x000003a5, 0x000003a9, 0x000003c3,
	0x000003ce, 0x000003e2, 0x000003ef, 0x00000405,
	0x0000040d, 0x0000041a, 0x0000042a, 0x00000435,
	0x00000442,
} // Size: 348 bytes

const en_USData string = "" + // Size: 1090 bytes
	"\x02Please use the full link.\x02Sorry, internal server error\x02Sorry, " +
	"not found\x02Create new Pad\x02These shifts have been marked as paid out" +
	" for\x02Time\x02Shift\x02Taker\x02Paid out\x02Unknown event\x02paid\x02h" +
	"ours\x02Sum\x02No shifts.\x02Paid shifts taken by\x02not yet approved" +
	"\x02Mark as paid out\x02Name\x02Description (Markdown)\x02Location\x02Sh" +
	"ift Names (one name per row)\x02ical Overlay\x02Save\x02Back\x02This is " +
	"your customized share link\x02Copy link\x02Administrate this Pad\x02Admi" +
	"nistrate this pad\x02Create, Edit and Delete Shifts\x02Any shift\x02Edit" +
	" retroactively\x02Payout\x02Mark any shift as paid out\x02Take Shifts" +
	"\x02Apply for Shifts\x02Take and Apply\x02Deadline (optional)\x02Cron ex" +
	"pression, example\x02Any taker name\x02Taker names\x02Take shifts as\x02" +
	"View Shifts\x02View taker name\x02View taker contact\x02Link Properties" +
	"\x02Expires\x02Note\x02Create share link\x02Cancel\x02Go\x02This\x02Next" +
	"\x02Error\x02Quantity\x02Edit\x02Delete\x02Approve\x02paid out\x02not pa" +
	"id out yet\x02Take\x02Apply\x02Create shifts\x02Unnamed Pad\x02Link expi" +
	"res\x02Copy iCalendar\x02Settings\x02Share\x02last changed\x02Begin\x02E" +
	"nd\x02do not assign to an event\x02Shift name\x02no shifts available\x02" +
	"Delete shift\x02Taker and Approvement\x02Contact\x02Save changes\x02Appl" +
	"y for shift\x02Take shift\x02Approve take"

	// Total table size 3166 bytes (3KiB); checksum: C34183FD
